### ISSUE TITLE
Keep url param `satisfaction` in sync with selection

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog-csat#2]
Currently, when someone visits https://survey.posthog.com/?satisfaction=4, we pre-select the specified rating (0 (lowest rating) - 4 (highest rating)).
![2024-02-05 at 13 44 56@2x](https://github.com/PostHog/posthog-csat/assets/13001502/e3de6986-7dcd-4686-bcdd-ac5526bdf605)

After clicking on another rating in the app, the change won't be reflected in the URL:
![2024-02-05 at 13 48 51@2x](https://github.com/PostHog/posthog-csat/assets/13001502/8ff46830-f72d-49bf-b244-fd56145b881a)

**Comment by oshodic** [comment]
I think this issue is occurring because the `searchParams` are not being updated properly. This could be fixed with using the `useEffect` hook to directly update the searchParams after setting `setSatisfaction` on line 38 in posthog-csat/src/pages/index.tsx file. A fix could look something like this:

`  useEffect(() => {
    searchParams.set('satisfaction', satisfaction.toString())
  }, [satisfaction])`

This way whenever the satisfaction state changes, the `searchParams` will reflect this change and be displayed in the URL. I would definitely want to do some testing first before implementing though.
